# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

language: node_js
node_js:
  - 12
cache:
  - npm
  - pip


jobs:
  include:

    - stage: Test
      before_script:
        - wget https://github.com/gohugoio/hugo/releases/download/v0.69.2/hugo_extended_0.69.2_Linux-64bit.deb
        - sudo dpkg -i hugo_extended_0.69.2_Linux-64bit.deb

    - stage: Publish
      script:
        - ./publish.sh "publish from travis build process,"
      if: branch = master

after_failure:
  - cat merge.log

import:
  - credentials.yml
  - .travis-stages.yml
  - .travis-merger.yml
